/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.css124l.finalcourseproject;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author John Mark Garcia
 */
public class main extends javax.swing.JFrame {
    /*
        How I structure the 2D array is similar to what is displayed in the UI:
        "vacant" = will turn the seat button GREEN
        "occupied" or any other words = will turn the seat button RED
    */
    
    JButton currentlySelectedSeat;
    static String[][] F1SeatList = {
        {"vacant", "vacant"},
        {"vacant", "vacant"},
        {"vacant", "vacant"},
        {"vacant", "vacant"}
    };
    static String[][] F2SeatList = {
        {"vacant", "vacant"},
        {"vacant", "vacant"},
        {"vacant", "vacant"},
        {"vacant", "vacant"}
    };
    public main() {
        initComponents();
        customizeSeatButtons(); 
       
        b_seat_1a.setBackground(Color.GREEN);
        b_seat_1b.setBackground(Color.GREEN);
        b_seat_2a.setBackground(Color.GREEN);
        b_seat_2b.setBackground(Color.GREEN);
        b_seat_3a.setBackground(Color.GREEN);
        b_seat_3b.setBackground(Color.GREEN);
        b_seat_4a.setBackground(Color.GREEN);
        b_seat_4b.setBackground(Color.GREEN);
    }
    
    public void CheckSeatList(String[][] SeatList) {
        
        if (SeatList[0][0] == "vacant") {b_seat_1a.setBackground(Color.green);}
        else {b_seat_1a.setBackground(Color.red);}
        
        if (SeatList[0][1] == "vacant") {b_seat_1b.setBackground(Color.green);}
        else {b_seat_1b.setBackground(Color.red);}
        
        if (SeatList[1][0] == "vacant") {b_seat_2a.setBackground(Color.green);}
        else {b_seat_2a.setBackground(Color.red);}
        
        if (SeatList[1][1] == "vacant") {b_seat_2b.setBackground(Color.green);}
        else {b_seat_2b.setBackground(Color.red);}
        
        if (SeatList[2][0] == "vacant") {b_seat_3a.setBackground(Color.green);}
        else {b_seat_3a.setBackground(Color.red);}
        
        if (SeatList[2][1] == "vacant") {b_seat_3b.setBackground(Color.green);}
        else {b_seat_3b.setBackground(Color.red);}
        
        if (SeatList[3][0] == "vacant") {b_seat_4a.setBackground(Color.green);}
        else {b_seat_4a.setBackground(Color.red);}
        
        if (SeatList[3][1] == "vacant") {b_seat_4b.setBackground(Color.green);}
        else {b_seat_4b.setBackground(Color.red);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_gender = new javax.swing.ButtonGroup();
        bg_additionalServices = new javax.swing.ButtonGroup();
        p_main = new javax.swing.JPanel();
        p_header = new javax.swing.JPanel();
        l_flightNumber = new javax.swing.JLabel();
        comB_flightNumber = new javax.swing.JComboBox<>();
        p_body = new javax.swing.JPanel();
        p_northbody = new java.awt.Panel();
        l_name = new java.awt.Label();
        tf_name = new java.awt.TextField();
        l_age = new java.awt.Label();
        tf_age = new java.awt.TextField();
        l_address = new java.awt.Label();
        tf_address = new java.awt.TextField();
        l_nationality = new java.awt.Label();
        cb_nationality = new javax.swing.JComboBox<>();
        l_gender = new java.awt.Label();
        rb_male = new javax.swing.JRadioButton();
        rb_female = new javax.swing.JRadioButton();
        rb_others = new javax.swing.JRadioButton();
        l_passportNumber = new java.awt.Label();
        tf_passportNumber = new java.awt.TextField();
        l_contactNumber = new java.awt.Label();
        tf_contactNumber = new java.awt.TextField();
        l_emailAddress = new java.awt.Label();
        tf_emailAddress = new java.awt.TextField();
        l_dateOfFlight = new java.awt.Label();
        tf_dateOfFlight = new java.awt.TextField();
        l_mealPreference = new java.awt.Label();
        cb_mealPreference = new javax.swing.JComboBox<>();
        l_departureAndDestination = new javax.swing.JLabel();
        cb_departureAndDestination = new javax.swing.JComboBox<>();
        p_centerbody = new javax.swing.JPanel();
        p_centerServices = new javax.swing.JPanel();
        l_additionalServices = new javax.swing.JLabel();
        cb_pwdAssistance = new javax.swing.JCheckBox();
        cb_extraBaggage = new javax.swing.JCheckBox();
        cb_extraSnacksAndDrinks = new javax.swing.JCheckBox();
        cb_priorityCheckInAndBoarding = new javax.swing.JCheckBox();
        p_centerSummary = new javax.swing.JPanel();
        l_flightCostSummary = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_flightCostSummary = new javax.swing.JTextArea();
        p_southbody = new java.awt.Panel();
        l_additionalNotes = new java.awt.Label();
        tf_additionalNotes = new java.awt.TextField();
        p_footer = new javax.swing.JPanel();
        b_clear = new javax.swing.JButton();
        b_confirm = new javax.swing.JButton();
        p_seats = new javax.swing.JPanel();
        p_seat_1a = new javax.swing.JPanel();
        b_seat_1a = new javax.swing.JButton();
        p_seat_1b = new javax.swing.JPanel();
        b_seat_1b = new javax.swing.JButton();
        p_seat_2a = new javax.swing.JPanel();
        b_seat_2a = new javax.swing.JButton();
        p_seat_2b = new javax.swing.JPanel();
        b_seat_2b = new javax.swing.JButton();
        p_seat_3a = new javax.swing.JPanel();
        b_seat_3a = new javax.swing.JButton();
        p_seat_3b = new javax.swing.JPanel();
        b_seat_3b = new javax.swing.JButton();
        p_seat_4a = new javax.swing.JPanel();
        b_seat_4a = new javax.swing.JButton();
        p_seat_4b = new javax.swing.JPanel();
        b_seat_4b = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        setResizable(false);

        p_main.setBorder(javax.swing.BorderFactory.createTitledBorder("Passenger Details"));
        p_main.setMinimumSize(new java.awt.Dimension(600, 600));
        p_main.setPreferredSize(new java.awt.Dimension(600, 600));
        p_main.setLayout(new java.awt.BorderLayout());

        l_flightNumber.setText("Flight Number");
        p_header.add(l_flightNumber);

        comB_flightNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F1", "F2" }));
        comB_flightNumber.setMinimumSize(new java.awt.Dimension(100, 22));
        comB_flightNumber.setPreferredSize(new java.awt.Dimension(100, 22));
        comB_flightNumber.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comB_flightNumberItemStateChanged(evt);
            }
        });
        p_header.add(comB_flightNumber);

        p_main.add(p_header, java.awt.BorderLayout.PAGE_START);

        l_name.setPreferredSize(new java.awt.Dimension(65, 20));
        l_name.setText("Name:");
        p_northbody.add(l_name);

        tf_name.setPreferredSize(new java.awt.Dimension(190, 20));
        p_northbody.add(tf_name);

        l_age.setPreferredSize(new java.awt.Dimension(45, 20));
        l_age.setText("Age:");
        p_northbody.add(l_age);

        tf_age.setPreferredSize(new java.awt.Dimension(200, 20));
        p_northbody.add(tf_age);

        l_address.setPreferredSize(new java.awt.Dimension(65, 20));
        l_address.setText("Address:");
        p_northbody.add(l_address);

        tf_address.setPreferredSize(new java.awt.Dimension(445, 20));
        p_northbody.add(tf_address);

        l_nationality.setPreferredSize(new java.awt.Dimension(65, 20));
        l_nationality.setText("Nationality:");
        p_northbody.add(l_nationality);

        cb_nationality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_nationality.setPreferredSize(new java.awt.Dimension(215, 22));
        p_northbody.add(cb_nationality);

        l_gender.setPreferredSize(new java.awt.Dimension(45, 20));
        l_gender.setText("Gender:");
        p_northbody.add(l_gender);

        bg_gender.add(rb_male);
        rb_male.setText("Male");
        p_northbody.add(rb_male);

        bg_gender.add(rb_female);
        rb_female.setText("Female");
        p_northbody.add(rb_female);

        bg_gender.add(rb_others);
        rb_others.setText("Others");
        p_northbody.add(rb_others);

        l_passportNumber.setPreferredSize(new java.awt.Dimension(105, 20));
        l_passportNumber.setText("Passport Number:");
        p_northbody.add(l_passportNumber);

        tf_passportNumber.setPreferredSize(new java.awt.Dimension(150, 20));
        p_northbody.add(tf_passportNumber);

        l_contactNumber.setText("Contact Number:");
        p_northbody.add(l_contactNumber);

        tf_contactNumber.setPreferredSize(new java.awt.Dimension(150, 20));
        p_northbody.add(tf_contactNumber);

        l_emailAddress.setText("Email Address:");
        p_northbody.add(l_emailAddress);

        tf_emailAddress.setPreferredSize(new java.awt.Dimension(420, 20));
        p_northbody.add(tf_emailAddress);

        l_dateOfFlight.setText("Date of Flight:");
        p_northbody.add(l_dateOfFlight);

        tf_dateOfFlight.setPreferredSize(new java.awt.Dimension(165, 20));
        p_northbody.add(tf_dateOfFlight);

        l_mealPreference.setText("Meal Preference:");
        p_northbody.add(l_mealPreference);

        cb_mealPreference.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_mealPreference.setPreferredSize(new java.awt.Dimension(155, 22));
        p_northbody.add(cb_mealPreference);

        l_departureAndDestination.setText("Departure & Destination:");
        p_northbody.add(l_departureAndDestination);

        cb_departureAndDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_departureAndDestination.setMinimumSize(new java.awt.Dimension(200, 22));
        cb_departureAndDestination.setPreferredSize(new java.awt.Dimension(200, 22));
        p_northbody.add(cb_departureAndDestination);

        p_centerServices.setLayout(new java.awt.GridLayout(5, 0));

        l_additionalServices.setText("Additional Services:");
        l_additionalServices.setAlignmentX(-1.0F);
        p_centerServices.add(l_additionalServices);

        bg_additionalServices.add(cb_pwdAssistance);
        cb_pwdAssistance.setText("PWD Assistance");
        p_centerServices.add(cb_pwdAssistance);

        bg_additionalServices.add(cb_extraBaggage);
        cb_extraBaggage.setText("Extra Baggage");
        p_centerServices.add(cb_extraBaggage);

        bg_additionalServices.add(cb_extraSnacksAndDrinks);
        cb_extraSnacksAndDrinks.setText("Extra Snacks & Drinks");
        p_centerServices.add(cb_extraSnacksAndDrinks);

        bg_additionalServices.add(cb_priorityCheckInAndBoarding);
        cb_priorityCheckInAndBoarding.setText("Priority Check in & Boarding");
        p_centerServices.add(cb_priorityCheckInAndBoarding);

        l_flightCostSummary.setText("Fligh Cost Summary:");

        ta_flightCostSummary.setColumns(20);
        ta_flightCostSummary.setRows(5);
        jScrollPane2.setViewportView(ta_flightCostSummary);

        javax.swing.GroupLayout p_centerSummaryLayout = new javax.swing.GroupLayout(p_centerSummary);
        p_centerSummary.setLayout(p_centerSummaryLayout);
        p_centerSummaryLayout.setHorizontalGroup(
            p_centerSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_centerSummaryLayout.createSequentialGroup()
                .addComponent(l_flightCostSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(p_centerSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        p_centerSummaryLayout.setVerticalGroup(
            p_centerSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_centerSummaryLayout.createSequentialGroup()
                .addComponent(l_flightCostSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout p_centerbodyLayout = new javax.swing.GroupLayout(p_centerbody);
        p_centerbody.setLayout(p_centerbodyLayout);
        p_centerbodyLayout.setHorizontalGroup(
            p_centerbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_centerbodyLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(p_centerServices, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_centerSummary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        p_centerbodyLayout.setVerticalGroup(
            p_centerbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_centerbodyLayout.createSequentialGroup()
                .addGroup(p_centerbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_centerServices, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_centerSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        p_southbody.setLayout(new java.awt.BorderLayout());

        l_additionalNotes.setPreferredSize(new java.awt.Dimension(200, 20));
        l_additionalNotes.setText("Additional Notes:");
        p_southbody.add(l_additionalNotes, java.awt.BorderLayout.CENTER);

        tf_additionalNotes.setPreferredSize(new java.awt.Dimension(300, 100));
        p_southbody.add(tf_additionalNotes, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout p_bodyLayout = new javax.swing.GroupLayout(p_body);
        p_body.setLayout(p_bodyLayout);
        p_bodyLayout.setHorizontalGroup(
            p_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_bodyLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(p_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p_southbody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(p_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(p_centerbody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p_northbody, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        p_bodyLayout.setVerticalGroup(
            p_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_northbody, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_centerbody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_southbody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        p_main.add(p_body, java.awt.BorderLayout.CENTER);

        b_clear.setText("Clear");
        b_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_clearActionPerformed(evt);
            }
        });
        p_footer.add(b_clear);

        b_confirm.setText("Confirm");
        b_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_confirmActionPerformed(evt);
            }
        });
        p_footer.add(b_confirm);

        p_main.add(p_footer, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(p_main, java.awt.BorderLayout.CENTER);

        p_seats.setBorder(javax.swing.BorderFactory.createTitledBorder("Seats"));
        p_seats.setMinimumSize(new java.awt.Dimension(200, 2));
        p_seats.setPreferredSize(new java.awt.Dimension(200, 600));
        p_seats.setLayout(new java.awt.GridLayout(4, 2));

        p_seat_1a.setLayout(new java.awt.BorderLayout());

        b_seat_1a.setBackground(new java.awt.Color(153, 255, 153));
        b_seat_1a.setText("1A");
        b_seat_1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_seat_1aActionPerformed(evt);
            }
        });
        p_seat_1a.add(b_seat_1a, java.awt.BorderLayout.CENTER);

        p_seats.add(p_seat_1a);

        p_seat_1b.setLayout(new java.awt.BorderLayout());

        b_seat_1b.setBackground(new java.awt.Color(153, 255, 153));
        b_seat_1b.setText("1B");
        b_seat_1b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_seat_1bActionPerformed(evt);
            }
        });
        p_seat_1b.add(b_seat_1b, java.awt.BorderLayout.CENTER);

        p_seats.add(p_seat_1b);

        p_seat_2a.setLayout(new java.awt.BorderLayout());

        b_seat_2a.setBackground(new java.awt.Color(153, 255, 153));
        b_seat_2a.setText("2A");
        b_seat_2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_seat_2aActionPerformed(evt);
            }
        });
        p_seat_2a.add(b_seat_2a, java.awt.BorderLayout.CENTER);

        p_seats.add(p_seat_2a);

        p_seat_2b.setLayout(new java.awt.BorderLayout());

        b_seat_2b.setBackground(new java.awt.Color(153, 255, 153));
        b_seat_2b.setText("2B");
        b_seat_2b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_seat_2bActionPerformed(evt);
            }
        });
        p_seat_2b.add(b_seat_2b, java.awt.BorderLayout.CENTER);

        p_seats.add(p_seat_2b);

        p_seat_3a.setLayout(new java.awt.BorderLayout());

        b_seat_3a.setBackground(new java.awt.Color(153, 255, 153));
        b_seat_3a.setText("3A");
        b_seat_3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_seat_3aActionPerformed(evt);
            }
        });
        p_seat_3a.add(b_seat_3a, java.awt.BorderLayout.CENTER);

        p_seats.add(p_seat_3a);

        p_seat_3b.setLayout(new java.awt.BorderLayout());

        b_seat_3b.setBackground(new java.awt.Color(153, 255, 153));
        b_seat_3b.setText("3B");
        b_seat_3b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_seat_3bActionPerformed(evt);
            }
        });
        p_seat_3b.add(b_seat_3b, java.awt.BorderLayout.CENTER);

        p_seats.add(p_seat_3b);

        p_seat_4a.setLayout(new java.awt.BorderLayout());

        b_seat_4a.setBackground(new java.awt.Color(153, 255, 153));
        b_seat_4a.setText("4A");
        b_seat_4a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_seat_4aActionPerformed(evt);
            }
        });
        p_seat_4a.add(b_seat_4a, java.awt.BorderLayout.CENTER);

        p_seats.add(p_seat_4a);

        p_seat_4b.setLayout(new java.awt.BorderLayout());

        b_seat_4b.setBackground(new java.awt.Color(153, 255, 153));
        b_seat_4b.setText("4B");
        b_seat_4b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_seat_4bActionPerformed(evt);
            }
        });
        p_seat_4b.add(b_seat_4b, java.awt.BorderLayout.CENTER);

        p_seats.add(p_seat_4b);

        getContentPane().add(p_seats, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comB_flightNumberItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comB_flightNumberItemStateChanged
        switch(comB_flightNumber.getSelectedItem().toString()) {
            case "F1":
                CheckSeatList(F1SeatList);
                break;
            case "F2":
                CheckSeatList(F2SeatList);
                break;
        }
    }//GEN-LAST:event_comB_flightNumberItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:\
        CheckSeatList(F1SeatList);
    }//GEN-LAST:event_formWindowOpened

    private void b_seat_1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_seat_1aActionPerformed
        // TODO add your handling code here:
         seatButtonClicked(b_seat_1a);
    }//GEN-LAST:event_b_seat_1aActionPerformed

    private void b_seat_1bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_seat_1bActionPerformed
        // TODO add your handling code here:
         seatButtonClicked(b_seat_1b);
    }//GEN-LAST:event_b_seat_1bActionPerformed

    private void b_seat_2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_seat_2aActionPerformed
        // TODO add your handling code here:
         seatButtonClicked(b_seat_2a);
    }//GEN-LAST:event_b_seat_2aActionPerformed

    private void b_seat_2bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_seat_2bActionPerformed
        // TODO add your handling code here:
         seatButtonClicked(b_seat_2b);
    }//GEN-LAST:event_b_seat_2bActionPerformed

    private void b_seat_3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_seat_3aActionPerformed
        // TODO add your handling code here:
         seatButtonClicked(b_seat_3a);
    }//GEN-LAST:event_b_seat_3aActionPerformed

    private void b_seat_3bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_seat_3bActionPerformed
        // TODO add your handling code here:
         seatButtonClicked(b_seat_3b);
    }//GEN-LAST:event_b_seat_3bActionPerformed

    private void b_seat_4aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_seat_4aActionPerformed
        // TODO add your handling code here:
         seatButtonClicked(b_seat_4a);
    }//GEN-LAST:event_b_seat_4aActionPerformed

    private void b_seat_4bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_seat_4bActionPerformed
        // TODO add your handling code here:
         seatButtonClicked(b_seat_4b);
    }//GEN-LAST:event_b_seat_4bActionPerformed

    private void b_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_confirmActionPerformed

        int result = JOptionPane.showConfirmDialog(this, "Do you want to confirm this booking?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
            String flightNumber = (String) comB_flightNumber.getSelectedItem();
            JOptionPane.showMessageDialog(this, "Flight Confirmed!\nFlight Number: " + flightNumber, "Confirmation", JOptionPane.INFORMATION_MESSAGE);
        }   
    }//GEN-LAST:event_b_confirmActionPerformed

    private void b_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_clearActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Do you want to clear all fields", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
            // clear all fields
        }   
    }//GEN-LAST:event_b_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    
     private void customizeSeatButtons() {
    b_seat_1a.setOpaque(true);
    b_seat_1a.setContentAreaFilled(true);
    b_seat_1a.setBorderPainted(true);
    b_seat_1a.setFocusPainted(false);
    b_seat_1a.setBackground(java.awt.Color.GREEN);
    
    b_seat_1b.setOpaque(true);
    b_seat_1b.setContentAreaFilled(true);
    b_seat_1b.setBorderPainted(true);
    b_seat_1b.setFocusPainted(false);
    b_seat_1b.setBackground(java.awt.Color.GREEN);
    
    b_seat_2a.setOpaque(true);
    b_seat_2a.setContentAreaFilled(true);
    b_seat_2a.setBorderPainted(true);
    b_seat_2a.setFocusPainted(false);
    b_seat_2a.setBackground(java.awt.Color.GREEN);
    
    b_seat_2b.setOpaque(true);
    b_seat_2b.setContentAreaFilled(true);
    b_seat_2b.setBorderPainted(true);
    b_seat_2b.setFocusPainted(false);
    b_seat_2b.setBackground(java.awt.Color.GREEN);
    
    b_seat_3a.setOpaque(true);
    b_seat_3a.setContentAreaFilled(true);
    b_seat_3a.setBorderPainted(true);
    b_seat_3a.setFocusPainted(false);
    b_seat_3a.setBackground(java.awt.Color.GREEN);
    
    b_seat_3b.setOpaque(true);
    b_seat_3b.setContentAreaFilled(true);
    b_seat_3b.setBorderPainted(true);
    b_seat_3b.setFocusPainted(false);
    b_seat_3b.setBackground(java.awt.Color.GREEN);
    
    b_seat_4a.setOpaque(true);
    b_seat_4a.setContentAreaFilled(true);
    b_seat_4a.setBorderPainted(true);
    b_seat_4a.setFocusPainted(false);
    b_seat_4a.setBackground(java.awt.Color.GREEN);
    
    b_seat_4b.setOpaque(true);
    b_seat_4b.setContentAreaFilled(true);
    b_seat_4b.setBorderPainted(true);
    b_seat_4b.setFocusPainted(false);
    b_seat_4b.setBackground(java.awt.Color.GREEN);
         
     }
          private void seatButtonClicked(JButton seatButton) {
              
    
    
        // If the seat is RED, do nothing (occupied)
        if (seatButton.getBackground().equals(Color.RED)) {
            return;
        }

        // If this seat is already selected (yellow), deselect it
        if (seatButton.getBackground().equals(Color.YELLOW)) {
            seatButton.setBackground(Color.GREEN);
            currentlySelectedSeat = null;
        } 
        // Otherwise, seat is green (vacant)
        else {
            // If another seat was selected, turn it green
            if (currentlySelectedSeat != null) {
               currentlySelectedSeat.setBackground(Color.GREEN);
            }
            // Mark this seat as selected
            seatButton.setBackground(Color.YELLOW);
            currentlySelectedSeat = seatButton;
        }
    }
          
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_clear;
    private javax.swing.JButton b_confirm;
    private javax.swing.JButton b_seat_1a;
    private javax.swing.JButton b_seat_1b;
    private javax.swing.JButton b_seat_2a;
    private javax.swing.JButton b_seat_2b;
    private javax.swing.JButton b_seat_3a;
    private javax.swing.JButton b_seat_3b;
    private javax.swing.JButton b_seat_4a;
    private javax.swing.JButton b_seat_4b;
    private javax.swing.ButtonGroup bg_additionalServices;
    private javax.swing.ButtonGroup bg_gender;
    private javax.swing.JComboBox<String> cb_departureAndDestination;
    private javax.swing.JCheckBox cb_extraBaggage;
    private javax.swing.JCheckBox cb_extraSnacksAndDrinks;
    private javax.swing.JComboBox<String> cb_mealPreference;
    private javax.swing.JComboBox<String> cb_nationality;
    private javax.swing.JCheckBox cb_priorityCheckInAndBoarding;
    private javax.swing.JCheckBox cb_pwdAssistance;
    private javax.swing.JComboBox<String> comB_flightNumber;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label l_additionalNotes;
    private javax.swing.JLabel l_additionalServices;
    private java.awt.Label l_address;
    private java.awt.Label l_age;
    private java.awt.Label l_contactNumber;
    private java.awt.Label l_dateOfFlight;
    private javax.swing.JLabel l_departureAndDestination;
    private java.awt.Label l_emailAddress;
    private javax.swing.JLabel l_flightCostSummary;
    private javax.swing.JLabel l_flightNumber;
    private java.awt.Label l_gender;
    private java.awt.Label l_mealPreference;
    private java.awt.Label l_name;
    private java.awt.Label l_nationality;
    private java.awt.Label l_passportNumber;
    private javax.swing.JPanel p_body;
    private javax.swing.JPanel p_centerServices;
    private javax.swing.JPanel p_centerSummary;
    private javax.swing.JPanel p_centerbody;
    private javax.swing.JPanel p_footer;
    private javax.swing.JPanel p_header;
    private javax.swing.JPanel p_main;
    private java.awt.Panel p_northbody;
    private javax.swing.JPanel p_seat_1a;
    private javax.swing.JPanel p_seat_1b;
    private javax.swing.JPanel p_seat_2a;
    private javax.swing.JPanel p_seat_2b;
    private javax.swing.JPanel p_seat_3a;
    private javax.swing.JPanel p_seat_3b;
    private javax.swing.JPanel p_seat_4a;
    private javax.swing.JPanel p_seat_4b;
    private javax.swing.JPanel p_seats;
    private java.awt.Panel p_southbody;
    private javax.swing.JRadioButton rb_female;
    private javax.swing.JRadioButton rb_male;
    private javax.swing.JRadioButton rb_others;
    private javax.swing.JTextArea ta_flightCostSummary;
    private java.awt.TextField tf_additionalNotes;
    private java.awt.TextField tf_address;
    private java.awt.TextField tf_age;
    private java.awt.TextField tf_contactNumber;
    private java.awt.TextField tf_dateOfFlight;
    private java.awt.TextField tf_emailAddress;
    private java.awt.TextField tf_name;
    private java.awt.TextField tf_passportNumber;
    // End of variables declaration//GEN-END:variables
}
